import * as yaml from 'js-yaml';

/**
 * Embedding server deployment mode in the unified install:
 * - 'native'   — host's local llama-server; container reaches it via host.docker.internal
 * - 'docker'   — bundled paparats-embed service in the compose stack
 * - 'external' — explicit EMBED_URL (skip both native detection and the docker service)
 */
export type EmbedMode = 'native' | 'docker' | 'external';

/** Embedding backend selected at install time. */
export type EmbeddingProvider = 'llama' | 'openai' | 'voyage';

/** Kept for support-mode compatibility in legacy install code. */
export type InstallMode = 'developer' | 'server' | 'support';

export interface LocalProjectMount {
  /** Project name (used as the basename under /projects/). */
  name: string;
  /** Absolute host path bind-mounted into the indexer container. */
  hostPath: string;
}

export interface UnifiedComposeConfig {
  embedMode: EmbedMode;
  /** Required when embedMode === 'external'. */
  embedUrl?: string;
  /** Embedding backend. Cloud providers skip the local embed server entirely. Default: 'llama'. */
  embeddingProvider?: EmbeddingProvider;
  /** When set, the dockerized Qdrant service is skipped. */
  qdrantUrl?: string;
  /** Stored in ~/.paparats/.env and referenced as ${QDRANT_API_KEY}. */
  qdrantApiKey?: string;
  /** Cron schedule for indexer (default: every 6 hours). */
  cron?: string;
  /** Local-path projects in projects.yml — added as bind-mounts on the indexer. */
  localProjects?: LocalProjectMount[];
  /** Absolute host path to ~/.paparats (used to mount projects.yml). */
  paparatsHome: string;
  /** Optional port overrides (test convenience). */
  ports?: {
    qdrant?: number;
    paparats?: number;
    embed?: number;
    indexer?: number;
  };
}

interface ComposeService {
  image: string;
  container_name: string;
  ports?: string[];
  environment?: Record<string, string>;
  extra_hosts?: string[];
  volumes?: string[];
  depends_on?: Record<string, { condition: string }>;
  healthcheck?: Record<string, unknown>;
  deploy?: Record<string, unknown>;
  logging?: Record<string, unknown>;
  restart?: string;
  networks?: string[];
}

interface ComposeFile {
  services: Record<string, ComposeService>;
  volumes: Record<string, null>;
  networks: Record<string, { driver: string; name: string }>;
}

const HEADER = `# paparats-mcp — Docker Compose (generated by paparats install)
# Managed file — regenerate with: paparats install
`;

function qdrantService(port: number): ComposeService {
  return {
    image: 'qdrant/qdrant:latest',
    container_name: 'paparats-qdrant',
    ports: [`\${QDRANT_PORT:-${port}}:6333`],
    volumes: ['qdrant_data:/qdrant/storage'],
    healthcheck: {
      test: ['CMD', 'bash', '-c', 'exec 3<>/dev/tcp/127.0.0.1/6333 || exit 1'],
      interval: '10s',
      timeout: '3s',
      retries: 3,
      start_period: '15s',
    },
    deploy: {
      resources: {
        limits: { cpus: '1.0', memory: '1G' },
        reservations: { cpus: '0.25', memory: '256M' },
      },
    },
    logging: { driver: 'json-file', options: { 'max-size': '10m', 'max-file': '3' } },
    restart: 'unless-stopped',
    networks: ['paparats-net'],
  };
}

function embedService(port: number): ComposeService {
  return {
    image: 'ibaz/paparats-embed:latest',
    container_name: 'paparats-embed',
    ports: [`\${EMBED_PORT:-${port}}:8080`],
    // EMBED_TTL: idle seconds before a model unloads. 0 = never (default) —
    // llama-swap's unload path can deadlock under load. Models are baked into
    // the image — no data volume needed.
    // LLAMA_BATCH: per-model compute-buffer batch size (default 2048). Larger
    // values inflate RSS with no gain on short embedding chunks — 8192 was the
    // cgroup-OOM culprit. LLAMA_THREADS: CPU threads per model (-1 = auto).
    environment: {
      EMBED_TTL: '${EMBED_TTL:-0}',
      LLAMA_BATCH: '${LLAMA_BATCH:-2048}',
      LLAMA_THREADS: '${LLAMA_THREADS:--1}',
    },
    healthcheck: {
      test: ['CMD', 'curl', '-fsS', 'http://localhost:8080/health'],
      interval: '10s',
      timeout: '5s',
      retries: 5,
      start_period: '30s',
    },
    // Two resident embedding models (bge-code-v1 + qwen3) each hold a compute
    // buffer sized by LLAMA_BATCH. With the 2048 default they fit comfortably in
    // 6G; raise the limit (and LLAMA_BATCH) for very large corpora, or lower it
    // on a constrained host. An explicit limit prevents a runaway model from
    // starving its siblings — the earlier OOM was an unbounded 8k-batch buffer.
    deploy: {
      resources: {
        limits: { cpus: '${EMBED_CPUS:-6.0}', memory: '${EMBED_MEMORY:-6G}' },
        reservations: { cpus: '1.0', memory: '2G' },
      },
    },
    logging: { driver: 'json-file', options: { 'max-size': '10m', 'max-file': '3' } },
    restart: 'unless-stopped',
    networks: ['paparats-net'],
  };
}

function paparatsService(
  port: number,
  embedUrl: string,
  qdrantUrl: string,
  includeQdrantDep: boolean,
  qdrantApiKey: string | undefined,
  embeddingProvider: EmbeddingProvider
): ComposeService {
  const dependsOn: Record<string, { condition: string }> = {};
  if (includeQdrantDep) {
    dependsOn['qdrant'] = { condition: 'service_healthy' };
  }

  const env: Record<string, string> = {
    QDRANT_URL: qdrantUrl,
  };
  if (embeddingProvider === 'llama') {
    env['EMBED_URL'] = embedUrl;
    env['EMBED_BATCH_SIZE'] = '${EMBED_BATCH_SIZE:-5}';
  } else {
    env['EMBEDDING_PROVIDER'] = embeddingProvider;
    if (embeddingProvider === 'openai') env['OPENAI_API_KEY'] = '${OPENAI_API_KEY:-}';
    if (embeddingProvider === 'voyage') env['VOYAGE_API_KEY'] = '${VOYAGE_API_KEY:-}';
  }
  // Arch-layer text embeddings — defaults track the qwen3-embedding-0.6b baked
  // into ibaz/paparats-embed. Override via .env when using a cloud provider or a
  // different text model.
  env['TEXT_EMBEDDING_MODEL'] = '${TEXT_EMBEDDING_MODEL:-qwen3-embedding-0.6b}';
  env['TEXT_EMBEDDING_DIMENSIONS'] = '${TEXT_EMBEDDING_DIMENSIONS:-1024}';
  if (qdrantApiKey) env['QDRANT_API_KEY'] = '${QDRANT_API_KEY}';
  // Resolve indexer over the docker-compose network so the analytics UI's
  // indexer tile reaches its sibling instead of the host loopback (which has
  // no service inside the container).
  env['PAPARATS_INDEXER_URL'] = 'http://paparats-indexer:9877';

  return {
    image: 'ibaz/paparats-server:latest',
    container_name: 'paparats-mcp',
    ports: [`\${PAPARATS_PORT:-${port}}:9876`],
    environment: env,
    extra_hosts: ['host.docker.internal:host-gateway'],
    volumes: ['paparats_data:/home/nodejs/.paparats'],
    depends_on: dependsOn,
    healthcheck: {
      test: [
        'CMD',
        'node',
        '-e',
        "require('http').get('http://localhost:9876/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1); }).on('error', () => process.exit(1));",
      ],
      interval: '30s',
      timeout: '3s',
      retries: 3,
      start_period: '10s',
    },
    deploy: {
      resources: {
        limits: { cpus: '2.0', memory: '2G' },
        reservations: { cpus: '0.5', memory: '512M' },
      },
    },
    logging: { driver: 'json-file', options: { 'max-size': '10m', 'max-file': '3' } },
    restart: 'unless-stopped',
    networks: ['paparats-net'],
  };
}

function indexerService(
  config: UnifiedComposeConfig,
  qdrantUrl: string,
  embedUrl: string,
  port: number,
  embeddingProvider: EmbeddingProvider
): ComposeService {
  const externalQdrant = !!config.qdrantUrl;
  const dockerEmbed = config.embedMode === 'docker' && embeddingProvider === 'llama';

  const dependsOn: Record<string, { condition: string }> = {};
  if (dockerEmbed) dependsOn['embed'] = { condition: 'service_healthy' };
  if (!externalQdrant) dependsOn['qdrant'] = { condition: 'service_healthy' };

  const env: Record<string, string> = {
    GITHUB_TOKEN: '${GITHUB_TOKEN:-}',
    CRON: `\${CRON:-${config.cron ?? '0 */6 * * *'}}`,
    QDRANT_URL: qdrantUrl,
  };
  if (embeddingProvider === 'llama') {
    env['EMBED_URL'] = embedUrl;
    env['EMBED_BATCH_SIZE'] = '${EMBED_BATCH_SIZE:-5}';
  } else {
    env['EMBEDDING_PROVIDER'] = embeddingProvider;
    if (embeddingProvider === 'openai') env['OPENAI_API_KEY'] = '${OPENAI_API_KEY:-}';
    if (embeddingProvider === 'voyage') env['VOYAGE_API_KEY'] = '${VOYAGE_API_KEY:-}';
  }
  if (config.qdrantApiKey) env['QDRANT_API_KEY'] = '${QDRANT_API_KEY}';

  // Mount the whole ~/.paparats as /config (directory bind-mount, not single file)
  // so the indexer survives in-place rewrites of projects.yml — single-file
  // bind-mounts pin to the host inode and break on atomic rename or replace.
  const volumes = [
    'indexer_repos:/data/repos',
    'paparats_data:/home/nodejs/.paparats',
    `${config.paparatsHome}:/config:ro`,
  ];
  for (const proj of config.localProjects ?? []) {
    volumes.push(`${proj.hostPath}:/projects/${proj.name}:ro`);
  }

  return {
    image: 'ibaz/paparats-indexer:latest',
    container_name: 'paparats-indexer',
    environment: env,
    ports: [`\${INDEXER_PORT:-${port}}:9877`],
    volumes,
    depends_on: dependsOn,
    extra_hosts: ['host.docker.internal:host-gateway'],
    logging: { driver: 'json-file', options: { 'max-size': '10m', 'max-file': '3' } },
    restart: 'unless-stopped',
    networks: ['paparats-net'],
  };
}

/**
 * Generate the unified docker-compose.yml — qdrant (optional) + embed (optional)
 * + paparats-server + paparats-indexer with mounts derived from `localProjects`.
 */
export function generateCompose(config: UnifiedComposeConfig): string {
  const qdrantPort = config.ports?.qdrant ?? 6333;
  const paparatsPort = config.ports?.paparats ?? 9876;
  const embedPort = config.ports?.embed ?? 18434;
  const indexerPort = config.ports?.indexer ?? 9877;

  const embeddingProvider: EmbeddingProvider = config.embeddingProvider ?? 'llama';
  const isCloud = embeddingProvider !== 'llama';

  const externalQdrant = !!config.qdrantUrl;
  // Cloud providers don't use the local embed server — drop the service and edges.
  const dockerEmbed = !isCloud && config.embedMode === 'docker';

  const qdrantUrl = externalQdrant ? config.qdrantUrl! : 'http://qdrant:6333';
  // For cloud providers the URL is irrelevant (the server reads
  // EMBEDDING_PROVIDER instead) — pass an empty string so we don't accidentally
  // wire host.docker.internal when the host has no embed server running.
  const embedUrl = isCloud ? '' : resolveEmbedUrl(config);

  const compose: ComposeFile = {
    services: {
      ...(externalQdrant ? {} : { qdrant: qdrantService(qdrantPort) }),
      ...(dockerEmbed ? { embed: embedService(embedPort) } : {}),
      paparats: paparatsService(
        paparatsPort,
        embedUrl,
        qdrantUrl,
        !externalQdrant,
        config.qdrantApiKey,
        embeddingProvider
      ),
      'paparats-indexer': indexerService(
        config,
        qdrantUrl,
        embedUrl,
        indexerPort,
        embeddingProvider
      ),
    },
    volumes: {
      ...(externalQdrant ? {} : { qdrant_data: null }),
      paparats_data: null,
      indexer_repos: null,
    },
    networks: {
      'paparats-net': { driver: 'bridge', name: 'paparats-network' },
    },
  };

  if (dockerEmbed) {
    compose.services['paparats']!.depends_on!['embed'] = { condition: 'service_healthy' };
  }

  return (
    HEADER +
    yaml.dump(compose, { lineWidth: 120, noRefs: true, quoteStyle: 'single', forceQuotes: false })
  );
}

function resolveEmbedUrl(config: UnifiedComposeConfig): string {
  switch (config.embedMode) {
    case 'docker':
      return 'http://embed:8080';
    case 'native':
      return 'http://host.docker.internal:18434';
    case 'external':
      if (!config.embedUrl) {
        throw new Error('generateCompose: embedMode="external" requires embedUrl');
      }
      return config.embedUrl;
  }
}
