import yaml from 'js-yaml';

export type OllamaMode = 'docker' | 'local';
export type InstallMode = 'developer' | 'server' | 'support';

export interface DockerComposeConfig {
  ollamaMode: OllamaMode;
  /** External Qdrant URL — when set, skip the Qdrant Docker service */
  qdrantUrl?: string;
  ports?: {
    qdrant?: number;
    paparats?: number;
    ollama?: number;
  };
}

export interface ServerComposeConfig extends DockerComposeConfig {
  repos?: string;
  githubToken?: string;
  cron?: string;
  /** When set, all repos share this single Qdrant group (collection) */
  group?: string;
  indexerPort?: number;
}

interface ComposeService {
  image: string;
  container_name: string;
  ports?: string[];
  environment?: Record<string, string>;
  extra_hosts?: string[];
  volumes?: string[];
  depends_on?: Record<string, { condition: string }>;
  healthcheck?: Record<string, unknown>;
  deploy?: Record<string, unknown>;
  logging?: Record<string, unknown>;
  restart?: string;
  networks?: string[];
}

interface ComposeFile {
  services: Record<string, ComposeService>;
  volumes: Record<string, null>;
  networks: Record<string, { driver: string; name: string }>;
}

function qdrantService(port: number): ComposeService {
  return {
    image: 'qdrant/qdrant:latest',
    container_name: 'paparats-qdrant',
    ports: [`\${QDRANT_PORT:-${port}}:6333`],
    volumes: ['qdrant_data:/qdrant/storage'],
    healthcheck: {
      test: ['CMD', 'bash', '-c', 'exec 3<>/dev/tcp/127.0.0.1/6333 || exit 1'],
      interval: '10s',
      timeout: '3s',
      retries: 3,
      start_period: '15s',
    },
    deploy: {
      resources: {
        limits: { cpus: '1.0', memory: '1G' },
        reservations: { cpus: '0.25', memory: '256M' },
      },
    },
    logging: { driver: 'json-file', options: { 'max-size': '10m', 'max-file': '3' } },
    restart: 'unless-stopped',
    networks: ['paparats-net'],
  };
}

function paparatsService(
  port: number,
  ollamaUrl: string,
  qdrantUrl: string,
  includeQdrantDep: boolean
): ComposeService {
  const dependsOn: Record<string, { condition: string }> = {};
  if (includeQdrantDep) {
    dependsOn['qdrant'] = { condition: 'service_healthy' };
  }

  return {
    image: 'ibaz/paparats-server:latest',
    container_name: 'paparats-mcp',
    ports: [`\${PAPARATS_PORT:-${port}}:9876`],
    environment: {
      QDRANT_URL: qdrantUrl,
      OLLAMA_URL: ollamaUrl,
    },
    extra_hosts: ['host.docker.internal:host-gateway'],
    volumes: ['paparats_data:/home/nodejs/.paparats'],
    depends_on: dependsOn,
    healthcheck: {
      test: [
        'CMD',
        'node',
        '-e',
        "require('http').get('http://localhost:9876/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1); }).on('error', () => process.exit(1));",
      ],
      interval: '30s',
      timeout: '3s',
      retries: 3,
      start_period: '10s',
    },
    deploy: {
      resources: {
        limits: { cpus: '2.0', memory: '2G' },
        reservations: { cpus: '0.5', memory: '512M' },
      },
    },
    logging: { driver: 'json-file', options: { 'max-size': '10m', 'max-file': '3' } },
    restart: 'unless-stopped',
    networks: ['paparats-net'],
  };
}

function ollamaService(port: number): ComposeService {
  return {
    image: 'ibaz/paparats-ollama:latest',
    container_name: 'paparats-ollama',
    ports: [`\${OLLAMA_PORT:-${port}}:11434`],
    volumes: ['ollama_data:/root/.ollama'],
    healthcheck: {
      test: ['CMD', 'wget', '-q', '-O', '/dev/null', 'http://localhost:11434/api/tags'],
      interval: '10s',
      timeout: '3s',
      retries: 5,
      start_period: '10s',
    },
    logging: { driver: 'json-file', options: { 'max-size': '10m', 'max-file': '3' } },
    restart: 'unless-stopped',
    networks: ['paparats-net'],
  };
}

function indexerService(config: ServerComposeConfig, qdrantUrl: string): ComposeService {
  const externalQdrant = !!config.qdrantUrl;

  const dependsOn: Record<string, { condition: string }> = {
    ollama: { condition: 'service_healthy' },
  };
  if (!externalQdrant) {
    dependsOn['qdrant'] = { condition: 'service_healthy' };
  }

  const env: Record<string, string> = {
    REPOS: '${REPOS:-}',
    GITHUB_TOKEN: '${GITHUB_TOKEN:-}',
    CRON: `\${CRON:-${config.cron ?? '0 */6 * * *'}}`,
    QDRANT_URL: qdrantUrl,
    OLLAMA_URL: 'http://ollama:11434',
  };
  if (config.group) {
    env['PAPARATS_GROUP'] = config.group;
  }

  const svc: ComposeService = {
    image: 'ibaz/paparats-indexer:latest',
    container_name: 'paparats-indexer',
    environment: env,
    ports: [`\${INDEXER_PORT:-${config.indexerPort ?? 9877}}:9877`],
    volumes: ['indexer_repos:/data/repos', 'paparats_data:/home/nodejs/.paparats'],
    depends_on: dependsOn,
    logging: { driver: 'json-file', options: { 'max-size': '10m', 'max-file': '3' } },
    restart: 'unless-stopped',
    networks: ['paparats-net'],
  };

  return svc;
}

const HEADER = `# paparats-mcp — Docker Compose (generated by paparats install)
# Managed file — regenerate with: paparats install
`;

/**
 * Generate docker-compose YAML for developer mode (qdrant + paparats + optional ollama).
 * When `config.qdrantUrl` is set, the Qdrant Docker service is omitted and the external URL is used.
 */
export function generateDockerCompose(config: DockerComposeConfig): string {
  const qdrantPort = config.ports?.qdrant ?? 6333;
  const paparatsPort = config.ports?.paparats ?? 9876;
  const ollamaPort = config.ports?.ollama ?? 11434;
  const externalQdrant = !!config.qdrantUrl;

  const ollamaUrl =
    config.ollamaMode === 'docker'
      ? 'http://ollama:11434'
      : '${OLLAMA_URL:-http://host.docker.internal:11434}';

  const qdrantUrl = externalQdrant ? config.qdrantUrl! : 'http://qdrant:6333';

  const compose: ComposeFile = {
    services: {
      ...(externalQdrant ? {} : { qdrant: qdrantService(qdrantPort) }),
      paparats: paparatsService(paparatsPort, ollamaUrl, qdrantUrl, !externalQdrant),
    },
    volumes: {
      ...(externalQdrant ? {} : { qdrant_data: null }),
      paparats_data: null,
    },
    networks: {
      'paparats-net': { driver: 'bridge', name: 'paparats-network' },
    },
  };

  if (config.ollamaMode === 'docker') {
    compose.services['ollama'] = ollamaService(ollamaPort);
    compose.services['paparats']!.depends_on!['ollama'] = { condition: 'service_healthy' };
    compose.volumes['ollama_data'] = null;
  }

  return (
    HEADER +
    yaml.dump(compose, { lineWidth: 120, noRefs: true, quotingType: "'", forceQuotes: false })
  );
}

/**
 * Generate docker-compose YAML for server mode (qdrant + paparats + ollama + indexer).
 * When `config.qdrantUrl` is set, the Qdrant Docker service is omitted and the external URL is used.
 */
export function generateServerCompose(config: ServerComposeConfig): string {
  const qdrantPort = config.ports?.qdrant ?? 6333;
  const paparatsPort = config.ports?.paparats ?? 9876;
  const ollamaPort = config.ports?.ollama ?? 11434;
  const externalQdrant = !!config.qdrantUrl;

  const qdrantUrl = externalQdrant ? config.qdrantUrl! : 'http://qdrant:6333';

  const compose: ComposeFile = {
    services: {
      ...(externalQdrant ? {} : { qdrant: qdrantService(qdrantPort) }),
      ollama: ollamaService(ollamaPort),
      paparats: paparatsService(paparatsPort, 'http://ollama:11434', qdrantUrl, !externalQdrant),
      'paparats-indexer': indexerService(config, qdrantUrl),
    },
    volumes: {
      ...(externalQdrant ? {} : { qdrant_data: null }),
      ollama_data: null,
      paparats_data: null,
      indexer_repos: null,
    },
    networks: {
      'paparats-net': { driver: 'bridge', name: 'paparats-network' },
    },
  };

  // paparats depends on ollama in server mode
  compose.services['paparats']!.depends_on!['ollama'] = { condition: 'service_healthy' };

  return (
    HEADER +
    yaml.dump(compose, { lineWidth: 120, noRefs: true, quotingType: "'", forceQuotes: false })
  );
}
